### PR TITLE
made the components

### PR DESCRIPTION
**Pull request by laerm0**
I made a few new glyphs (some combining marks, .numr and .dnom) so that I could make composite accented glyphs and fractions, which I have done.

### CODE REVIEW

**Comment by laerm0** [comment]
Hey @eliheuer, this is good to go now. We have five FB errors:

```
>> com.google.fonts/check/028
   Check font has a license.
 * FAIL: No license file was found. Please add an OFL.txt or a LICENSE.txt file. If you are running fontbakery on a Google Fonts upstream repo, which is fine, just make sure there is a temporary license file in the same folder. [code: none]

   Result: FAIL

>> com.google.fonts/check/001 with (('font[0]', 'Dosis-VF_VTT.ttf'),)
   Checking file is named canonically.
 * FAIL: Style name used in "Dosis-VF_VTT.ttf" is not canonical. You should rebuild the font using any of the following style names: "Thin", "ExtraLight", "Light", "Regular", "Medium", "SemiBold", "Bold", "ExtraBold", "Black", "Thin Italic", "ExtraLight Italic", "Light Italic", "Italic", "Medium Italic", "SemiBold Italic", "Bold Italic", "ExtraBold Italic", "Black Italic".

   Result: FAIL

>> com.google.fonts/check/072 with (('font[0]', 'Dosis-VF_VTT.ttf'),)
   Font enables smart dropout control in "prep" table instructions?
 * FAIL: 'prep' table does not contain TrueType  instructions enabling smart dropout control. To fix, export the font with autohinting enabled, or run ttfautohint on the font, or run the  `gftools fix-nonhinting` script.

   Result: FAIL

>> com.google.fonts/check/053 with (('font[0]', 'Dosis-VF_VTT.ttf'),)
   Are there unwanted tables?
 * FAIL: Unwanted tables were found in the font and should be removed: TSI0, TSI1, TSI2, TSI3, TSI5

   Result: FAIL

>> com.google.fonts/check/045 with (('font[0]', 'Dosis-VF_VTT.ttf'),)
   Does the font have a DSIG table?
 * FAIL: This font lacks a digital signature (DSIG table). Some applications may require one (even if only a dummy placeholder) in order to work properly.

   Result: FAIL
```

I think 072 should be skipped for VTT hinted fonts. I will report to Felipe.

**Comment by eliheuer** [comment]
Awesome, thanks!
- check/028: This check is broken, obviously there is a license.
- check/001: I will need to rename the file to `Dosis-Regular.ttf` for the PR.
- check/072: Felipe will know what to do with this. 
- check/053: This is new, maybe from VTT
- check/045: There is a script to add a dummy table. I will run that on the new VTT file.

**Comment by laerm0** [comment]
Yep, 053 is from VTT. That's the hint source. Can't delete those!

072 Felipe and I can coordinate on.

**Comment by eliheuer** [comment]
I updated the DSIG table with commit 9f03e35

**Pull request merged**
